/* Pure, deterministic renderer. Shared by Canvas playback and SVG visual QA. */
(function(root){
'use strict';
const C={bg:'#121716',ink:'#d1d8d3',muted:'#84918b',faint:'#35413b',line:'#57665d',teal:'#91b8aa',amber:'#c7ae82',red:'#bc8e7b'};
const clamp=(x,a=0,b=1)=>Math.max(a,Math.min(b,x));
const lerp=(a,b,t)=>a+(b-a)*t;
const add=(a,b)=>a.map((v,i)=>v+b[i]),sub=(a,b)=>a.map((v,i)=>v-b[i]),mul=(a,s)=>a.map(v=>v*s);
const norm=a=>Math.hypot(...a);
const cross=(a,b)=>[a[1]*b[2]-a[2]*b[1],a[2]*b[0]-a[0]*b[2],a[0]*b[1]-a[1]*b[0]];
const unit=a=>mul(a,1/(norm(a)||1));
const dot=(a,b)=>a.reduce((s,v,i)=>s+v*b[i],0);
function sampleFrame(states,progress){const x=clamp(progress)*(states.length-1),index=Math.floor(x),next=Math.min(index+1,states.length-1);return{state:states[index],next:states[next],index,nextIndex:next,t:x-index};}
function quat(T){let m=T,t=m[0][0]+m[1][1]+m[2][2],q;if(t>0){let s=Math.sqrt(t+1)*2;q=[(m[2][1]-m[1][2])/s,(m[0][2]-m[2][0])/s,(m[1][0]-m[0][1])/s,s/4];}else{let i=m[0][0]>m[1][1]?(m[0][0]>m[2][2]?0:2):(m[1][1]>m[2][2]?1:2),j=(i+1)%3,k=(i+2)%3,s=Math.sqrt(1+m[i][i]-m[j][j]-m[k][k])*2;q=[0,0,0,0];q[i]=s/4;q[j]=(m[j][i]+m[i][j])/s;q[k]=(m[k][i]+m[i][k])/s;q[3]=(m[k][j]-m[j][k])/s;}return unit(q);}
function blendPose(A,B,t){if(!B||t===0)return A;if(t===1)return B;let a=quat(A),b=quat(B),d=dot(a,b);if(d<0){b=mul(b,-1);d=-d;}let q;if(d>.9995)q=unit(a.map((v,i)=>lerp(v,b[i],t)));else{let theta=Math.acos(clamp(d,-1,1)),sn=Math.sin(theta);q=a.map((v,i)=>(v*Math.sin((1-t)*theta)+b[i]*Math.sin(t*theta))/sn);}let[x,y,z,w]=q;return[[1-2*y*y-2*z*z,2*x*y-2*z*w,2*x*z+2*y*w,lerp(A[0][3],B[0][3],t)],[2*x*y+2*z*w,1-2*x*x-2*z*z,2*y*z-2*x*w,lerp(A[1][3],B[1][3],t)],[2*x*z-2*y*w,2*y*z+2*x*w,1-2*x*x-2*y*y,lerp(A[2][3],B[2][3],t)],[0,0,0,1]];}
const origin=T=>[T[0][3],T[1][3],T[2][3]];
const apply=(T,p)=>T.slice(0,3).map(row=>dot(row.slice(0,3),p)+row[3]);
function invApply(T,p){let d=sub(p,origin(T));return[0,1,2].map(i=>T[0][i]*d[0]+T[1][i]*d[1]+T[2][i]*d[2]);}
function intr(K){if(Array.isArray(K))return {fx:K[0][0],fy:K[1][1],cx:K[0][2],cy:K[1][2]};return K;}
function project(T,p,K){const q=invApply(T,p),k=intr(K);return[k.fx*q[0]/q[2]+k.cx,k.fy*q[1]/q[2]+k.cy];}
const blendPts=(a,b,t)=>a.map((v,i)=>v.map((n,j)=>lerp(n,b[i][j],t)));
function projector(points,box,yaw=.66,pitch=.38){let u=[Math.cos(yaw),0,-Math.sin(yaw)],v=[Math.sin(yaw)*Math.sin(pitch),-Math.cos(pitch),Math.cos(yaw)*Math.sin(pitch)],proj=p=>[dot(u,p),dot(v,p)],raw=points.map(proj),xs=raw.map(p=>p[0]),ys=raw.map(p=>p[1]);let lo=[Math.min(...xs),Math.min(...ys)],hi=[Math.max(...xs),Math.max(...ys)],s=Math.min(box[2]/Math.max(hi[0]-lo[0],.01),box[3]/Math.max(hi[1]-lo[1],.01))*.82,c=[(lo[0]+hi[0])/2,(lo[1]+hi[1])/2];return p=>{let q=proj(p);return[box[0]+box[2]/2+(q[0]-c[0])*s,box[1]+box[3]/2+(q[1]-c[1])*s]};}
class CanvasRenderer{constructor(ctx){this.ctx=ctx;}rect(x,y,w,h,c,alpha=1,stroke=null){let q=this.ctx;q.globalAlpha=alpha;if(c){q.fillStyle=c;q.fillRect(x,y,w,h);}if(stroke){q.strokeStyle=stroke;q.lineWidth=1;q.strokeRect(x,y,w,h);}q.globalAlpha=1;}line(a,b,c,width=1,alpha=1,dash=[]){const q=this.ctx;q.beginPath();q.strokeStyle=c;q.lineWidth=width;q.globalAlpha=alpha;q.setLineDash(dash);q.moveTo(...a);q.lineTo(...b);q.stroke();q.setLineDash([]);q.globalAlpha=1;}poly(p,c,width=1,alpha=1,closed=false,fill=null){if(!p.length)return;const q=this.ctx;q.beginPath();q.moveTo(...p[0]);p.slice(1).forEach(p=>q.lineTo(...p));if(closed)q.closePath();q.globalAlpha=alpha;if(fill){q.fillStyle=fill;q.fill();}q.strokeStyle=c;q.lineWidth=width;q.stroke();q.globalAlpha=1;}circle(x,y,r,c,alpha=1,stroke=null){const q=this.ctx;q.beginPath();q.arc(x,y,r,0,Math.PI*2);q.globalAlpha=alpha;if(c){q.fillStyle=c;q.fill();}if(stroke){q.strokeStyle=stroke;q.lineWidth=1;q.stroke();}q.globalAlpha=1;}text(str,x,y,size=12,c=C.muted,alpha=1,align='left',font='mono'){const q=this.ctx;q.globalAlpha=alpha;q.fillStyle=c;q.font=`${size}px ${font==='mono'?'ui-monospace, SFMono-Regular, Consolas, monospace':'Arial, sans-serif'}`;q.textAlign=align;q.textBaseline='alphabetic';q.fillText(str,x,y);q.globalAlpha=1;}}
function esc(s){return String(s).replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/"/g,'&quot;');}
class SVGRenderer{constructor(w=1600,h=850){this.w=w;this.h=h;this.items=[];}rect(x,y,w,h,c,alpha=1,stroke=null){this.items.push(`<rect x="${x}" y="${y}" width="${w}" height="${h}" fill="${c||'none'}" opacity="${alpha}" stroke="${stroke||'none'}"/>`);}line(a,b,c,width=1,alpha=1,dash=[]){this.items.push(`<line x1="${a[0]}" y1="${a[1]}" x2="${b[0]}" y2="${b[1]}" stroke="${c}" stroke-width="${width}" opacity="${alpha}" stroke-dasharray="${dash.join(',')}"/>`);}poly(p,c,width=1,alpha=1,closed=false,fill=null){this.items.push(`<${closed?'polygon':'polyline'} points="${p.map(p=>p.join(',')).join(' ')}" stroke="${c}" stroke-width="${width}" opacity="${alpha}" fill="${fill||'none'}"/>`);}circle(x,y,r,c,alpha=1,stroke=null){this.items.push(`<circle cx="${x}" cy="${y}" r="${r}" fill="${c||'none'}" stroke="${stroke||'none'}" opacity="${alpha}"/>`);}text(str,x,y,size=12,c=C.muted,alpha=1,align='left',font='mono'){this.items.push(`<text x="${x}" y="${y}" fill="${c}" opacity="${alpha}" font-size="${size}" font-family="${font==='mono'?'DejaVu Sans Mono':'DejaVu Sans'}" text-anchor="${align==='center'?'middle':align==='right'?'end':'start'}">${esc(str)}</text>`);}toString(){return `<svg xmlns="http://www.w3.org/2000/svg" width="${this.w}" height="${this.h}" viewBox="0 0 1600 850"><rect width="1600" height="850" fill="${C.bg}"/>${this.items.join('\n')}</svg>`;}}
function axes(R,T,P,size=.5,alpha=.8){let o=P(origin(T));[C.amber,C.teal,C.ink].forEach((c,i)=>{let p=[0,0,0];p[i]=size;R.line(o,P(apply(T,p)),c,1.2,alpha);});R.circle(...o,2,C.ink,alpha);}
function camera(R,T,P,size=.45,accent=false,anchor=false){let o=P(origin(T)),p=[[-.7,-.44,1],[.7,-.44,1],[.7,.44,1],[-.7,.44,1]].map(p=>P(apply(T,mul(p,size)))),c=accent?C.amber:C.muted;R.poly(p,c,1,accent?.95:.65,true);p.forEach(pt=>R.line(o,pt,c,1,accent?.65:.3));R.circle(...o,anchor?4:3,anchor?C.ink:c,.9);if(anchor)R.circle(...o,7,null,.7,C.muted);}
function base(R,mode,background){R.rect(0,0,1600,850,C.bg);for(let x=60;x<1600;x+=36)for(let y=68;y<850;y+=36)R.circle(x,y,.65,C.muted,.095);R.line([60,71],[1540,71],C.line,.6,.5);if(!background){R.text('GEOMETRY / OPTIMIZATION / CONTROL',60,48,11,C.muted,.85);R.text('SYNTHETIC STUDY   ·   COMPUTED TRACES',1540,48,11,C.muted,.85,'right');}R.line([1040,130],[1040,752],C.line,.65,background?.14:.3);}
function label(R,k,title,x,y,background){if(background)return;R.text(k,x,y,10,C.amber,.8);R.text(title,x,y+24,15,C.ink,.9,'left','sans');}
function curve(R,states,index,key,box,background,labelText,log=true){const[x,y,w,h]=box,vals=states.map(s=>s[key]),valid=vals.filter(v=>Number.isFinite(v)&&v>0);if(!valid.length)return;let lo=Math.min(...valid),hi=Math.max(...valid);if(log){lo=Math.log10(Math.max(lo,1e-12));hi=Math.log10(hi);}if(hi-lo<.001)hi=lo+1;const at=(i,v)=>[x+i/(states.length-1||1)*w,y+h-(clamp(((log?Math.log10(Math.max(v,1e-12)):v)-lo)/(hi-lo)))*h];[0,.5,1].forEach(t=>R.line([x,y+t*h],[x+w,y+t*h],C.line,.6,.25));const pts=vals.map((v,i)=>at(i,v));R.poly(pts,C.muted,1,.18);R.poly(pts.slice(0,index+1),C.teal,1.6,.95);R.circle(...pts[index],3,C.teal,1);R.line([pts[index][0],y],[pts[index][0],y+h],C.teal,1,.2);if(!background){R.text(labelText,x,y-18,10,C.muted);R.text(log?'LOG SCALE':'',x+w,y-18,9,C.muted,.7,'right');R.text('INITIAL',x,y+h+24,9,C.muted);R.text('FINAL',x+w,y+h+24,9,C.muted,.8,'right');}}
function imagePlane(R,cameraT,pts,observations,K,width,height,box,accentCam,background){const[x,y,w,h]=box,s=Math.min(w/width,h/height),ox=x+(w-width*s)/2,oy=y+(h-height*s)/2;R.rect(ox,oy,width*s,height*s,null,.55,C.line);R.line([ox+width*s/2,oy],[ox+width*s/2,oy+height*s],C.line,.7,.22);R.line([ox,oy+height*s/2],[ox+width*s,oy+height*s/2],C.line,.7,.22);observations.filter(o=>o.camera===accentCam).forEach(o=>{const uv=project(cameraT,pts[o.point],K),a=[ox+o.uv[0]*s,oy+o.uv[1]*s],b=[ox+uv[0]*s,oy+uv[1]*s];if([...a,...b].some(n=>!Number.isFinite(n)))return;R.line(a,b,C.amber,1,.65);R.circle(...a,2.3,null,.7,C.teal);R.line([b[0]-2,b[1]],[b[0]+2,b[1]],C.ink,1,.8);R.line([b[0],b[1]-2],[b[0],b[1]+2],C.ink,1,.8);});if(!background)R.text(`CAM ${String(accentCam).padStart(2,'0')} / OBSERVED ↔ PROJECTED`,x,y-13,10,C.muted);}
function sparse(R,data,s,box,background){const[x,y,w,h]=box,free=data.freeCameraIndices||[2,3,4,5],nc=free.length,np=s.points.length,cw=w/(nc+np),rows=data.observations.length,rh=h/rows;data.observations.forEach((o,k)=>{let ci=free.indexOf(o.camera);if(ci>=0)R.rect(x+ci*cw,y+k*rh,cw*.75,Math.max(.8,rh*.7),C.amber,.65);R.rect(x+(nc+o.point)*cw,y+k*rh,cw*.75,Math.max(.8,rh*.7),C.teal,.5);});R.line([x+nc*cw-2,y-9],[x+nc*cw-2,y+h],C.ink,.5,.35);if(!background){R.text('J / OBSERVATION-BLOCK SPARSITY',x,y-22,10,C.muted);R.text(`${rows} residual blocks × ${nc+np} parameter blocks`,x,y+h+22,9,C.muted,.7);}const S=s.linearization&&s.linearization.schurBlockNorms;if(S){let n=S.length,max=Math.max(...S.flat(),1e-9),xx=x+120,yy=y+h+83,cell=22;S.forEach((row,i)=>row.forEach((v,j)=>{R.rect(xx+j*cell,yy+i*cell,cell-3,cell-3,C.amber,.08+.8*Math.sqrt(Math.abs(v)/max));}));if(!background){R.text('SCHUR / CAMERA COUPLING',x,yy-16,10,C.muted);R.text('S = B − E C⁻¹ Eᵀ',x+132,yy+cell*n+30,12,C.ink,.8,'center');}}}
function renderBA(R,data,progress,background){const q=sampleFrame(data.states,progress),s=q.state,n=q.next,t=q.t,cams=s.cameras.map((T,i)=>blendPose(T,n.cameras[i],t)),pts=blendPts(s.points,n.points,t),all=[...data.truth.points,...data.states[0].points,...data.truth.cameras.map(origin),...data.states[0].cameras.map(origin)],P=projector(all,[80,145,880,480],.6,.37),active=2+Math.floor(progress*11)%Math.max(1,cams.length-2);label(R,'01 / JOINT RECONSTRUCTION','Bundle adjustment',80,107,background);const path=data.truth.cameras.map(T=>P(origin(T)));R.poly(path,C.line,.8,.3);data.observations.forEach((o,i)=>{if(i%5!==0&&o.camera!==active)return;R.line(P(origin(cams[o.camera])),P(pts[o.point]),o.camera===active?C.amber:C.line,.7,o.camera===active?.11:.1);});pts.forEach((p,j)=>{let truth=P(data.truth.points[j]),cur=P(p);R.line(truth,cur,C.teal,.6,.25);R.circle(...truth,1.8,null,.2,C.muted);R.circle(...cur,j%7===0?3.2:2,C.teal,j%7===0?.95:.65);});cams.forEach((T,i)=>{camera(R,T,P,.5,i===active,i<2);if(!background){let c=P(origin(T));R.text(`${i<2?'● ':''}C${i}`,c[0],c[1]+21,10,i===active?C.amber:C.muted,.85,'center');}});for(let i=0;i<3;i++){let o=data.observations[(Math.floor(progress*data.observations.length)+i*19)%data.observations.length],a=P(origin(cams[o.camera])),b=P(pts[o.point]),phase=(progress*16+i*.31)%1;R.circle(lerp(a[0],b[0],phase),lerp(a[1],b[1],phase),1.7,C.amber,.8);}imagePlane(R,cams[active],pts,data.observations,data.intrinsics,data.width,data.height,[85,617,360,168],active,background);if(!background){R.text('SE(3) POSES + 3D LANDMARKS',490,681,11,C.muted);R.text('min Σ ρ( ‖u − π(KT⁻¹P)‖² )',490,711,18,C.ink,.75);R.text('LM STEP  →  SCHUR ELIMINATION  →  RETRACTION',490,740,9,C.muted,.7);R.text('Two fixed cameras anchor frame + metric scale',490,770,10,C.muted,.8);}sparse(R,data,s,[1110,145,350,199],background);curve(R,data.states,q.index,'cost',[1110,584,350,134],background,'ROBUST OBJECTIVE / ACCEPTED ITERATES');if(!background){R.text(`k ${String(q.index).padStart(2,'0')}    cost ${s.cost.toExponential(2)}    λ ${s.lambda.toExponential(1)}`,1110,764,10,C.ink,.8);R.text(`inlier RMS  ${s.inlierRmsePx.toFixed(3)} px`,1110,790,11,C.muted);}}
function mult(A,B){return A.map((row,i)=>row.map((_,j)=>row.reduce((sum,x,k)=>sum+x*B[k][j],0)));}
function renderHand(R,data,progress,background){const q=sampleFrame(data.states,progress),s=q.state,X=blendPose(s.X,q.next.X,q.t),pairs=data.pairs,path=data.motionPath,all=[...path.map(origin),...path.map(T=>origin(mult(T,data.truthX))),[0,0,0]],P=projector(all,[100,164,840,515],.7,.33),active=Math.min(pairs.length-1,Math.floor(progress*(pairs.length-.01))),pair=pairs[active],left=mult(pair.A,X),right=mult(X,pair.B);label(R,'02 / RIGID TRANSFORM CONSISTENCY','Hand–eye calibration',80,107,background);R.poly(path.map(T=>P(origin(T))),C.ink,1.4,.5);R.poly(path.map(T=>P(origin(mult(T,X)))),C.teal,1.4,.65);path.forEach((T,i)=>{axes(R,T,P,.1,.25);let S=mult(T,X);camera(R,S,P,.10,i===active%path.length);R.line(P(origin(T)),P(origin(S)),C.line,.8,.3);});let O=[[1,0,0,0],[0,1,0,0],[0,0,1,0],[0,0,0,1]],p0=P([0,0,0]);axes(R,O,P,.4,.8);axes(R,left,P,.38,.95);axes(R,right,P,.38,.95);let a=P(origin(left)),b=P(origin(right));R.line(a,b,C.amber,2,.9,[4,4]);R.circle(...a,6,null,1,C.amber);R.circle(...b,5,null,1,C.teal);if(!background){R.text('AᵢX',a[0]+13,a[1]-10,12,C.amber);R.text('XBᵢ',b[0]+13,b[1]+22,12,C.teal);R.text('ROBOT MOTION',90,720,10,C.ink);R.text('CAMERA MOTION',255,720,10,C.teal);R.text('AᵢX = XBᵢ',80,779,26,C.ink,.8);R.text('min Σ ρ( ‖Log((AᵢX)⁻¹XBᵢ)∨‖²Ω )',350,777,16,C.muted,.9);}const xx=1110,yy=145,cell=60;X.forEach((row,i)=>row.forEach((v,j)=>{R.rect(xx+j*cell,yy+i*cell,cell-6,cell-6,j===3?C.amber:C.teal,.025+.16*Math.min(1,Math.abs(v)));if(!background)R.text(v.toFixed(3),xx+j*cell+(cell-6)/2,yy+i*cell+31,11,C.ink,.85,'center');}));if(!background){R.text('X / ESTIMATED EXTRINSIC',xx,yy-22,10,C.muted);R.text('ROTATION + TRANSLATION',xx,yy+269,10,C.muted);}curve(R,data.states,q.index,'cost',[1110,580,350,140],background,'WHITENED ROBUST OBJECTIVE');if(!background){R.text(`k ${String(q.index).padStart(2,'0')}   rotation ${s.rotationErrorDeg.toFixed(4)}°`,1110,767,11,C.ink,.85);R.text(`translation ${s.translationError.toExponential(2)} m`,1110,793,11,C.muted);}}
function renderServo(R,data,progress,background){const q=sampleFrame(data.states,progress),s=q.state,pose=blendPose(s.pose,q.next.pose,q.t),pts=data.worldPoints,all=[...pts,...data.states.map(s=>origin(s.pose)),origin(data.targetPose)],P=projector(all,[80,176,470,510],.8,.3),path=data.states.map(s=>P(origin(s.pose)));label(R,'03 / CLOSED-LOOP CONTROL','Image-based visual servoing',80,107,background);R.poly(path,C.line,1,.6);R.poly(path.slice(0,q.index+1),C.teal,1.6,.85);camera(R,data.targetPose,P,.23,false);camera(R,pose,P,.3,true);pts.forEach(p=>{R.circle(...P(p),3,C.teal,.9);R.line(P(origin(pose)),P(p),C.line,1,.3);});R.poly([...pts.map(P),P(pts[0])],C.muted,1,.5);const K=data.intrinsics,w=data.width,h=data.height,x=600,y=208,pw=363,ph=pw*h/w,sc=pw/w,pix=pts.map(p=>project(pose,p,K));R.rect(x,y,pw,ph,null,.8,C.line);for(let i=1;i<4;i++){R.line([x+i*pw/4,y],[x+i*pw/4,y+ph],C.line,.6,.3);R.line([x,y+i*ph/4],[x+pw,y+i*ph/4],C.line,.6,.3);}data.targetPixels.forEach((p,i)=>{let a=[x+p[0]*sc,y+p[1]*sc],b=[x+pix[i][0]*sc,y+pix[i][1]*sc],trail=data.states.slice(0,q.index+1).map(s=>[x+s.pixels[i][0]*sc,y+s.pixels[i][1]*sc]);R.poly(trail,C.amber,1,.45);R.line(a,b,C.amber,1,.8);R.rect(a[0]-4,a[1]-4,8,8,null,.8,C.teal);R.circle(...b,3.3,C.ink,.95);});if(!background){R.text('IMAGE PLANE / FEATURE TRAJECTORIES',x,y-23,10,C.muted);R.text('TARGET',x,y+ph+30,10,C.teal);R.text('CURRENT',x+106,y+ph+30,10,C.ink);R.text('ṡ = L(s,Z) v',80,741,24,C.ink,.85);R.text('v = −α (LᵀL + μ²I)⁻¹ Lᵀe',80,785,20,C.muted,.95);R.text('KNOWN SYNTHETIC DEPTH · DAMPED CONTROL',600,741,9,C.muted);R.text('Pose integrated on SE(3)',600,775,12,C.muted);}const vv=s.velocity||[],mx=Math.max(.1,...data.states.flatMap(s=>s.velocity.map(Math.abs)));if(!background)R.text('CAMERA TWIST / ACTUAL CONTROL OUTPUT',1110,143,10,C.muted);['vₓ','vᵧ','v_z','ωₓ','ωᵧ','ω_z'].forEach((name,i)=>{let yy=191+i*42,val=vv[i]||0,len=val/mx*110;R.line([1183,yy],[1430,yy],C.line,.6,.35);R.line([1305,yy-11],[1305,yy+11],C.line,.6,.5);R.rect(len<0?1305+len:1305,yy-5,Math.abs(len),10,i<3?C.teal:C.amber,.7);if(!background){R.text(name,1110,yy+4,12,C.muted);R.text(val.toFixed(3),1470,yy+4,10,C.muted,.9,'right');}});curve(R,data.states,q.index,'errorPx',[1110,580,350,141],background,'IMAGE ERROR / RMS PIXELS');if(!background){R.text(`t ${s.time.toFixed(2)} s     RMS ${s.errorPx.toFixed(3)} px`,1110,767,11,C.ink,.9);R.text('translation: m/s   rotation: rad/s',1110,793,10,C.muted);}}
function renderFrame(R,data,mode,progress,options={}){let background=!!options.background;base(R,mode,background);if(mode==='ba')renderBA(R,data.bundleAdjustment,progress,background);else if(mode==='hand')renderHand(R,data.handEye,progress,background);else if(mode==='servo')renderServo(R,data.visualServo,progress,background);else throw new Error('Unknown mode');return R;}
const api={C,clamp,sampleFrame,blendPose,project,CanvasRenderer,SVGRenderer,renderFrame};if(typeof module!=='undefined')module.exports=api;root.AlgorithmVisual=api;
})(typeof window!=='undefined'?window:globalThis);
